[package]
name = "image-processor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argparse-rs = { git = "https://github.com/joyanedel/argparser-rs", version = "0.1.0" }
image = "0.25.1"
